### ISSUE TITLE
Some tests have undefined behavior

### ISSUE THREAD

**Issue by tyfkda** [hsjoihs/c-compiler#1]
In test_cases.sh, some cases write to out of range,
so causes `*** stack smashing detected ***`
if I use `gcc` instead of `./out/compiler.out`.

Illegal tests are 

[case 242](https://github.com/hsjoihs/c-compiler/blob/master/test_cases.sh#L237):

```
run_test 242 'int main(){int a[1][2];int (*p)[2];p = a;int *q;q = *(p+1); *q=174; return **(a+1);}' 174
```

[case 125](https://github.com/hsjoihs/c-compiler/blob/master/test_cases.sh#L332):

```
run_test 125 'int main(){int a[1][2];int *q;q = *(a+1); *q=174; return **(a+1);}' 174
```

**Comment by hsjoihs** [comment]
Thank you! Fixed.
